### ISSUE TITLE
При закрытии коннекта всегда падает

### ISSUE THREAD

**Issue by xtron** [tarantool/tarantool-java#17]
```
public class Test {
   private static final String tntUserName = "tnt";
    private static final String tntPassword = "tnt";
    private static final String tntHost = "localhost";
    private static final int tntPort = 3301;
    private static TarantoolClient tntClient;

    @BeforeClass
    public static void initConnection() {
        TarantoolClientConfig config = new TarantoolClientConfig();
        config.username = tntUserName;
        config.password = tntPassword;
        tntClient = new TarantoolClientImpl((int retryNumber, Throwable lastError) -> {
            if (lastError != null) {
                lastError.printStackTrace(System.out);
            }
            try {
                return SocketChannel.open(new InetSocketAddress(tntHost, tntPort));
            } catch (IOException e) {
                throw new IllegalStateException(e);
            }
        }, config);
    }

    @AfterClass
    public static void closeConnection() {
        if (tntClient != null) {
            tntClient.close();
        }
    }
}
```

Получаю такой вывод
```

org.tarantool.CommunicationException: Cant write bytes
	at org.tarantool.TarantoolClientImpl.die(TarantoolClientImpl.java:241)
	at org.tarantool.TarantoolClientImpl.writeThread(TarantoolClientImpl.java:395)
	at org.tarantool.TarantoolClientImpl$3.run(TarantoolClientImpl.java:170)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
```

```
Tarantool 1.7.2-378-g05b487e
Target: Linux-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -fno-gnu89-inline
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-invalid-offsetof
```

**Comment by xtron** [comment]
Решено. был вывод здесь
 if (lastError != null) {
                lastError.printStackTrace(System.out);
            }
