### ISSUE TITLE
NPE on auth with tarantool 1.6.7

### ISSUE THREAD

**Issue by bashnesnos** [tarantool/tarantool-java#5]
I'm getting the following stack trace when connecting with the 1.6.4 to a tarantool 1.6.7
```
java.lang.NullPointerException
	at java.util.EnumMap.typeCheck(EnumMap.java:740)
	at java.util.EnumMap.put(EnumMap.java:266)
	at org.tarantool.ConnectionState.toKeyMap(ConnectionState.java:69)
	at org.tarantool.ConnectionState.unpack(ConnectionState.java:56)
	at org.tarantool.TarantoolConnection16Base.readPacket(TarantoolConnection16Base.java:76)
	at org.tarantool.TarantoolConnection16Base.read(TarantoolConnection16Base.java:69)
	at org.tarantool.TarantoolConnection16Impl.exec(TarantoolConnection16Impl.java:26)
	at org.tarantool.TarantoolConnection16Base.auth(TarantoolConnection16Base.java:153)

**Comment by bigbes** [comment]
It seems like it was caused by new field 'IPROTO_SCHEMA' in header. It was added in Tarantool 1.6.7.

**Comment by dgreenru** [comment]
I did processing of unknown keys fault tolerant. 1.6.5 will be accessible in central in 10 minutes.

**Comment by bashnesnos** [comment]
Спасибо!
